# Generated by Django 5.0.6 on 2025-04-30 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('admin_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Administrator',
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_id', models.CharField(max_length=255, null=True, unique=True)),
                ('tier_level', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Badge',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='HealthCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_card_id', models.CharField(max_length=255, null=True, unique=True)),
                ('health_card_name', models.CharField(max_length=255)),
                ('health_card_description', models.TextField()),
            ],
            options={
                'db_table': 'Health_Card',
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_time', models.CharField(max_length=255, null=True)),
                ('record_date', models.CharField(max_length=255, null=True)),
                ('session_id', models.IntegerField(unique=True)),
                ('session_duration', models.FloatField(null=True)),
                ('session_date', models.CharField(max_length=255, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='welcomePage.department')),
                ('health_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='welcomePage.healthcard')),
            ],
            options={
                'db_table': 'Health_Record',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='welcomePage.department')),
            ],
            options={
                'db_table': 'Team',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_teams', to='welcomePage.team'),
        ),
        migrations.CreateModel(
            name='TeamSummary',
            fields=[
                ('team_sum_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('vote_average', models.FloatField(null=True)),
                ('progress_trend', models.CharField(max_length=255, null=True)),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_summaries', to='welcomePage.healthrecord')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_summaries', to='welcomePage.team')),
            ],
            options={
                'db_table': 'Team_Summary',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='team_summary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='welcomePage.teamsummary'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='team_summary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='welcomePage.teamsummary'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('role', models.CharField(max_length=255)),
                ('session_id', models.IntegerField(null=True, unique=True)),
                ('session_duration', models.FloatField(null=True)),
                ('session_date', models.CharField(max_length=255, null=True)),
                ('view_profile', models.CharField(max_length=255, null=True)),
                ('profile_picture', models.BinaryField(null=True)),
                ('login_error_times', models.IntegerField(null=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='welcomePage.administrator')),
                ('badge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='welcomePage.badge')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='SKYEAI',
            fields=[
                ('chat_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('prompt', models.TextField(null=True)),
                ('response', models.TextField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skye_ai_chats', to='welcomePage.user')),
            ],
            options={
                'db_table': 'SKYE-AI',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='welcomePage.user'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('vote_value', models.FloatField(null=True)),
                ('progress_status', models.CharField(max_length=255, null=True)),
                ('vote_comment', models.TextField(null=True)),
                ('health_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='welcomePage.healthcard')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='welcomePage.user')),
            ],
            options={
                'db_table': 'Vote',
            },
        ),
    ]
