# Generated by Django 5.0.6 on 2025-04-30 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('admin_id', models.TextField(blank=True, db_column='Admin_Id', primary_key=True, serialize=False)),
                ('email', models.TextField(blank=True, db_column='Email', null=True, unique=True)),
                ('password', models.TextField(blank=True, db_column='Password', null=True)),
            ],
            options={
                'db_table': 'Administrator',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.TextField(blank=True, db_column='User_Id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('email', models.TextField(blank=True, db_column='Email', null=True, unique=True)),
                ('password', models.TextField(blank=True, db_column='Password', null=True)),
                ('role', models.CharField(blank=True, db_column='Role', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(blank=True, db_column='admin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='welcomePage.administrator')),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.TextField(blank=True, db_column='Department_Id', primary_key=True, serialize=False)),
                ('department_name', models.TextField(db_column='Department_Name')),
                ('user', models.ForeignKey(db_column='User_Id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Department',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, db_column='Department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='welcomePage.department'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.TextField(blank=True, db_column='Team_Id', primary_key=True, serialize=False)),
                ('team_name', models.TextField(db_column='Team_Name')),
                ('depart', models.ForeignKey(blank=True, db_column='Depart_Id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='welcomePage.department')),
            ],
            options={
                'db_table': 'Team',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='department',
            name='team',
            field=models.ForeignKey(db_column='Team_Id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='welcomePage.team'),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, db_column='team_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='welcomePage.team'),
        ),
    ]
