# Generated by Django 5.0.6 on 2025-04-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcomePage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='depart',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='department',
            name='team',
        ),
        migrations.RemoveField(
            model_name='department',
            name='user',
        ),
    ]
