# Generated by Django 5.0.6 on 2025-04-30 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomePage', '0002_rename_depart_team_department_remove_department_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.AlterField(
            model_name='team',
            name='department',
            field=models.ForeignKey(blank=True, db_column='Depart_Id', default='nullDep', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='welcomePage.department'),
            preserve_default=False,
        ),
    ]
