# Generated by Django 5.0.6 on 2025-04-30 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomePage', '0003_remove_user_department_remove_user_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, db_column='Depart_Id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='welcomePage.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, db_column='Team_Id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='welcomePage.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='department',
            field=models.ForeignKey(blank=True, db_column='Depart_Id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='welcomePage.department'),
        ),
    ]
