# Generated by Django 5.0.6 on 2025-05-01 00:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('welcomePage', '0004_user_department_user_team_alter_team_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('badge_id', models.TextField(blank=True, db_column='Badge_Id', primary_key=True, serialize=False)),
                ('tier_level', models.TextField(blank=True, db_column='Tier_Level', null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HealthCard',
            fields=[
                ('health_card_id', models.AutoField(db_column='Health_Card_Id', primary_key=True, serialize=False)),
                ('health_card_name', models.TextField(db_column='Health_Card_Name')),
                ('health_card_description', models.TextField(blank=True, db_column='Health_Card_Description', null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('record_id', models.AutoField(db_column='Record_Id', primary_key=True, serialize=False)),
                ('record_time', models.DateTimeField(blank=True, db_column='Record_Time', null=True)),
                ('record_date', models.DateField(blank=True, db_column='Record_Date', null=True)),
                ('session_id', models.IntegerField(db_column='Session_Id', unique=True)),
                ('session_duration', models.DurationField(blank=True, db_column='Session_Duration', null=True)),
                ('session_date', models.DateField(blank=True, db_column='Session_Date', null=True)),
                ('depart', models.ForeignKey(blank=True, db_column='Depart_Id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='welcomePage.department')),
                ('health_card', models.ForeignKey(blank=True, db_column='Health_Card_Id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='surveyPage.healthcard')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SkyeAi',
            fields=[
                ('chat_id', models.TextField(blank=True, db_column='Chat_Id', primary_key=True, serialize=False)),
                ('prompt', models.TextField(blank=True, db_column='Prompt', null=True)),
                ('response', models.TextField(blank=True, db_column='Response', null=True)),
                ('user', models.ForeignKey(blank=True, db_column='User_Id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skye_ai', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SKYE-AI',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TeamSummary',
            fields=[
                ('team_sum_id', models.TextField(blank=True, db_column='Team_Sum_Id', primary_key=True, serialize=False)),
                ('vote_average', models.FloatField(blank=True, db_column='Vote_Average', null=True)),
                ('progress_trend', models.TextField(blank=True, db_column='Progress_Trend', null=True)),
                ('record', models.ForeignKey(blank=True, db_column='Record_Id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_summaries', to='surveyPage.healthrecord')),
                ('team', models.ForeignKey(blank=True, db_column='Team_Id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_summaries', to='welcomePage.team')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='team_sum',
            field=models.ForeignKey(blank=True, db_column='Team_Sum_Id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='surveyPage.teamsummary'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.AutoField(db_column='Vote_Id', primary_key=True, serialize=False)),
                ('vote_value', models.IntegerField(blank=True, choices=[(1, 'Bad'), (2, 'Neutral'), (3, 'Good')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('progress_status', models.TextField(blank=True, db_column='Progress_Status', null=True)),
                ('vote_comment', models.TextField(blank=True, db_column='Vote_Comment', null=True)),
                ('health_card', models.ForeignKey(blank=True, db_column='Health_Card_Id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='surveyPage.healthcard')),
                ('user', models.ForeignKey(blank=True, db_column='User_Id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
